export const appName = 'FQuantWeb'
export const appFullName = 'FQUant Web Application'
export const appDescription = 'FQuant Web Application, Quant Market A。'
export const version = '3.1.4.0919'
export const author = 'annodomini189'
export const email = 'hhha@sina.com'
export const powerby = 'Nuxt3 + QuasarUI'